import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { getSupabaseAdmin } from '@/lib/supabase/admin';
import { loggers } from '@/lib/logger';

/**
 * GET /api/tax/ebupot-pph23/pdf?transactionId=xxx
 *
 * Returns a printable HTML Bukti Potong PPh 23 for a single transaction.
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) return new NextResponse('Unauthorized', { status: 401 });

    const txId = new URL(request.url).searchParams.get('transactionId');
    if (!txId) return new NextResponse('transactionId required', { status: 400 });

    const admin = getSupabaseAdmin();
    const { data: tx } = await admin.from('pph23_transaction').select('*').eq('id', txId).single();
    if (!tx) return new NextResponse('Transaction not found', { status: 404 });

    const { data: customer } = await admin.from('customer').select('company_name, full_name, npwp').eq('id', tx.customer_id).single();
    const pemotong = customer?.company_name || customer?.full_name || '-';
    const pemotongNpwp = customer?.npwp || '-';
    const fmtRp = (n: number) => `Rp ${n.toLocaleString('id-ID')}`;

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Bukti Potong PPh 23 - ${tx.bukti_potong_number || 'DRAFT'}</title>
<style>
body{font-family:'Courier New',monospace;max-width:700px;margin:30px auto;padding:20px;font-size:12px}
.border-box{border:2px solid #000;padding:15px;margin-bottom:10px}
h1{text-align:center;font-size:16px;text-decoration:underline}
h2{text-align:center;font-size:12px;font-weight:normal}
.row{display:flex;margin:3px 0}.label{width:180px;font-weight:bold}.value{flex:1}
table{width:100%;border-collapse:collapse;margin:10px 0}
th,td{border:1px solid #000;padding:5px;font-size:11px}
th{background:#f0f0f0}
.right{text-align:right}
</style></head><body>
<div class="border-box" style="text-align:center">
<h2>BUKTI PEMOTONGAN PPh PASAL 23</h2>
<h1>${tx.bukti_potong_number || 'BELUM DITERBITKAN'}</h1>
</div>
<div class="border-box">
<div style="font-weight:bold;text-decoration:underline;margin-bottom:8px">PEMOTONG PAJAK</div>
<div class="row"><span class="label">Nama</span><span class="value">: ${pemotong}</span></div>
<div class="row"><span class="label">NPWP</span><span class="value">: ${pemotongNpwp}</span></div>
</div>
<div class="border-box">
<div style="font-weight:bold;text-decoration:underline;margin-bottom:8px">PENERIMA PENGHASILAN</div>
<div class="row"><span class="label">Nama</span><span class="value">: ${tx.counterparty_name || '-'}</span></div>
<div class="row"><span class="label">NPWP</span><span class="value">: ${tx.counterparty_npwp || 'TIDAK ADA'}</span></div>
</div>
<table>
<thead><tr><th>Jenis Penghasilan</th><th class="right">DPP (Rp)</th><th>Tarif</th><th class="right">PPh Dipotong (Rp)</th></tr></thead>
<tbody>
<tr><td>${tx.service_type || '-'}</td><td class="right">${fmtRp(Number(tx.gross_amount))}</td><td>${(Number(tx.tax_rate) * 100).toFixed(1)}%</td><td class="right">${fmtRp(Number(tx.tax_amount))}</td></tr>
</tbody>
</table>
<div class="border-box">
<div class="row"><span class="label">Tanggal Pemotongan</span><span class="value">: ${tx.bukti_potong_date || tx.transaction_date || '-'}</span></div>
<div class="row"><span class="label">Invoice</span><span class="value">: ${tx.invoice_number || '-'}</span></div>
</div>
<div style="text-align:right;margin-top:30px">
<div>Tempat, ${new Date().toLocaleDateString('id-ID')}</div>
<div style="margin-top:40px"><b>${pemotong}</b></div>
</div>
<div style="margin-top:20px;font-size:9px;color:#999;text-align:center">Generated by AI Pajak × Jakarta Tax Consulting</div>
</body></html>`;

    return new NextResponse(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } });
  } catch (error) {
    loggers.api.error({ err: error }, 'e-Bupot PDF error');
    return new NextResponse('Failed', { status: 500 });
  }
}
