import { chromium } from 'playwright';
const CHROME = `${process.env.HOME}/Library/Caches/ms-playwright/chromium_headless_shell-1208/chrome-headless-shell-mac-arm64/chrome-headless-shell`;
const b = await chromium.launch({ headless: true, executablePath: CHROME });
const ctx = await b.newContext({ viewport: { width: 1280, height: 800 }, locale: 'id-ID' });
const page = await ctx.newPage();
await page.goto('http://localhost:3000/id/login', { waitUntil: 'networkidle' });
await page.fill('input[type="text"]', 'company.test@example.com');
await page.fill('input[type="password"]', 'TestPassword123!');
await page.click('button[type="submit"]');
await page.waitForURL(u => !u.pathname.includes('/login'), { timeout: 15000 });
await page.waitForTimeout(1500);
// Try /id/tax (no index page)
await page.goto('http://localhost:3000/id/tax', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
await page.screenshot({ path: '.gstack/qa-reports/screenshots/404-branded.png' });
const body = (await page.textContent('body')) || '';
const has404 = body.includes('404');
const hasBrand = body.includes('Halaman') || body.includes('Dasbor');
console.log(`has 404: ${has404}, has branded copy: ${hasBrand}`);
console.log('body snippet:', body.slice(0, 300));
await b.close();
