-- Add missing activity_type enum values for audit logging

-- Add TAX_FILING_SUBMIT
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'TAX_FILING_SUBMIT';

-- Add TAX_FILING_UPDATE
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'TAX_FILING_UPDATE';

-- Add TAX_FILING_STATUS_CHANGE
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'TAX_FILING_STATUS_CHANGE';

-- Add BILLING_CREATE
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'BILLING_CREATE';

-- Add POA activity types (some may already exist)
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'POA_CREATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'POA_SIGNED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'POA_ACTIVATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'POA_REVOKED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'POA_CUSTOMER_SIGNED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'POA_ADVISOR_SIGNED';

-- Add TAX_CALCULATION
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'TAX_CALCULATION';

-- Add LOGIN_SUCCESS / LOGIN_FAILURE for security auditing
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'LOGIN_SUCCESS';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'LOGIN_FAILURE';

COMMENT ON TYPE activity_type IS 'All possible audit log activity types';
